### ISSUE TITLE
Application not working after upgrade laraval 10 from 9

### ISSUE THREAD

**Issue by racechand** [innocenzi/laravel-vite#344] opened 2023-02-17 16:16 UTC
Hi Support,

Application not working after upgrade laraval 10 from 9

Migrating URL : https://laravel.com/docs/10.x/upgrade#updating-dependencies

Error Message: 
{"status":false,"message":"Innocenzi\\Vite\\HeartbeatCheckers\\HttpHeartbeatChecker::ping(): Argument #1 ($url) must be of type string, null given, called in D:\\xampp\\htdocs\\th-web-vite\\vendor\\innocenzi\\laravel-vite\\src\\Configuration.php

Version in the Composer Json :  "innocenzi/laravel-vite": "^0.3.1"

Please give solutions for this issue.

**Comment by innocenzi** [comment] 2023-02-17 18:35
Have you changed your `config/vite.php`? If not, can you provide me with a simple reproduction?

Also, I highly suggest moving to the official Vite implementation from the Laravel team. I'm no longer using this package myself since it has become redundant with the official one.

**Closed by innocenzi** 2023-02-17 18:35 UTC
